FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

# Exponer el puerto 5173 para el servidor de desarrollo de Vite
EXPOSE 5173


CMD ["npm", "run", "dev", "--", "--host"]