version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app  
      - /app/node_modules  

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: parranda
      POSTGRES_PASSWORD: navidad
      POSTGRES_DB: parranda-navideña
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
