version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env  # ✅ Explicitly load .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    volumes:
      - ./media:/app/media  # ✅ Persistencia de imágenes

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    env_file:
      - .env  # ✅ Explicitly load .env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app  
      - /app/node_modules 
    environment:
      - VITE_BACKEND_URL=http://localhost:8000  # ✅ React (Vite) uses VITE_ prefix
      - VITE_CLOUDINARY_CLOUD_NAME: ${VITE_CLOUDINARY_CLOUD_NAME}
      - VITE_CLOUDINARY_UPLOAD_PRESET: ${VITE_CLOUDINARY_UPLOAD_PRESET}

  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env  # ✅ Explicitly load .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  media:  # ✅ Volumen persistente para imágenes
